# Generated by Django 4.2.6 on 2023-10-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=6)),
                ('zona', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
