# Generated by Django 4.2.6 on 2023-11-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ace_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('indice_bairro', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('bairro_nome', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bairros', to='ace_api.bairro')),
            ],
            options={
                'ordering': ['bairro_nome'],
            },
        ),
    ]
