# Generated by Django 4.2.6 on 2023-11-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_api', '0002_bairro_indice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indice',
            name='indice_bairro',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True),
        ),
    ]
